### ISSUE TITLE
Docker won't start after I edit config

### ISSUE THREAD

**Issue by cpaczek** [cmccambridge/mosquitto-unraid#13]
I pretty sure I am just doing this wrong but I am trying to setup a broker for home assistant and I can't get anything to work at all.
I want to just the standard mqtt protocol  on port 1883 with logging

```
# Place your local configuration in /mqtt/config/conf.d/


persistence true
persistence_location /mosquitto/data/

user mosquitto

# Port to use for the default listener.
port 1883
protocol mqtt


log_dest file /mosquitto/log/mosquitto.log
log_type information

include_dir /mqtt/config/conf.d
```
I start it and it just stops again.

**Comment by cmccambridge** [comment]
Hi @Cpaczek - apologies for the very late response, I somehow missed the notification go by that this issue was filed.
Are you still having this issue and need any help sorting it out? I use this as an MQTT broker for home assistant as well.

The configuration you've posted looks like it may be a generic example that needs customization. For this unraid-specific docker container, I've tried to set things up to integrate more smoothly with unraid's concept of "appdata" directories, and allowing a user to map configuration files from that path. These unraid-specific mappings are captured in the README, as well as in the unraid template published in the Community Apps store.

For logging, specifically, please see the documentation section on [enabling logging](https://github.com/cmccambridge/mosquitto-unraid#logging), which would have you add only a few lines to your `mosquitto.conf` (or a new file, e.g. `logging.conf`). In the default community applications configuration, you would find this at `/mnt/user/appdata/mosquitto/mosquitto.conf`, and you would need to provide another mapping for the "Log Directory" parameter in the docker manager.

**Comment by cmccambridge** [comment]
I'm going to go ahead and close this out since I haven't seen any updates in the past few months, but please feel free to reopen it @Cpaczek if you're still having any issues!
