### ISSUE TITLE
I'm not able to install the docker on my Unraid

### ISSUE THREAD

**Issue by fiveredcars** [cmccambridge/mosquitto-unraid#40]
Im not able to install the docker
May you help me

docker run
  -d
  --name='mosquitto'
  --net='bridge'
  -e TZ="America/Los_Angeles"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="elcobert"
  -e HOST_CONTAINERNAME="mosquitto"
  -e 'RUN_INSECURE_MQTT_SERVER'='1'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/cmccambridge/mosquitto-unraid/master/media/eclipse-mosquitto.png'
  -p '1883:1883/tcp'
  -p ':8883/tcp'
  -p ':9001/tcp'
  -v '/mnt/user/appdata/mosquitto':'/mosquitto/config':'rw'
  -v '':'/mosquitto/data':'rw'
  -v '':'/mosquitto/log':'rw' 'cmccambridge/mosquitto-unraid:latest'
docker: invalid spec: :/mosquitto/data:rw: empty section between colons.
See 'docker run --help'.

The command failed.

Thank you

**Comment by fiveredcars** [comment]
Solved indicating the Persistent Data Directory and the lock path.

**Comment by cmccambridge** [comment]
Glad to hear!

Yes, the persistent data and log directories need to either be set to valid values *OR* removed from the template altogether so that they are not supplied with empty values.

Note: If you choose not to provide a path for persistent data or logs, that can be OK, but be careful: If you turn on persistent data or logging without providing volume mounts, then data or logs generated while running will be written within the container image instead. This will temporarily consume disk space, and then be *lost* when the container is stopped and removed.
